### PR TITLE
Port to GTK4

### PR DESCRIPTION
**Pull request by ZenitsuDev**
Aims to go with https://github.com/elementary/switchboard/pull/231

Blocked by :
- [x] [Depends on switchboard](https://github.com/elementary/switchboard/pull/231)

### CODE REVIEW

**Comment by ZenitsuDev** [comment]
@danrabbit I have tried this with the draft switchboard and it seems to be working fine. I might clean up a little too, so it follows the code style

**Comment by jeremypw** [comment]
@ZenitsuDev I think this PR should be targeted at the `main` branch not `master`?  The Gtk4 version of switchboard is already merged there.

**Review by jeremypw — CHANGES_REQUESTED** [review]
I haven't looked at the code in detail yet - just installed it alongside the switchboard from the `main` branch. First observations are that the window can shrink smaller than can accommodate the list. Either we are going to have to have the plugs accomodate smaller widths/heights gracefully or set minimum dimensions

**Comment by jeremypw** [comment]
Clipping with minimum window width.
Screenshot from 2022-07-04 19 36 17

**Comment by jeremypw** [comment]
The minimum width of the window in `master` is much wider so the problem does not arise. Need at least to set some margins?

**Comment by ZenitsuDev** [comment]
> The minimum width of the window in `master` is much wider so the problem does not arise. Need at least to set some margins?

I think so... I'll try setting some values later

**Comment by jeremypw** [comment]
@ZenitsuDev Actually I think better approach is to use a Clamp (see Dani's work).

**Comment by ZenitsuDev** [comment]
Yes I saw it, i'll take it as basis for the other plugs that might need it also :)

**Comment by ZenitsuDev** [comment]
@jeremypw I have put it inside a clamp, but can you check it? Thank you!

**Comment by jeremypw** [comment]
A simpler solution seems to be to put the Network time switch and associated widgets in a box, the same with the Show Week Numbers switch and widgets.  You can then put all the boxes in a single grid column rather than using 3 columns.

This is what I get:

Screenshot from 2022-07-11 08 52 45

**Comment by ZenitsuDev** [comment]
@jeremypw , Pardon me for I am afraid I do not get what you are implying here, 

> A simpler solution seems to be to put the Network time switch and associated widgets in a box, the same with the Show Week Numbers switch and widgets. You can then put all the boxes in a single grid column rather than using 3 columns.
> 
> This is what I get:
> 
> Screenshot from 2022-07-11 08 52 45

If it is okay, please feel free to push to this PR. Thank you!

**Comment by jeremypw** [comment]
@ZenitsuDev Sorry for not being clear.  I have pushed the changes I suggested. Also fixed the CI.

The timezone grid should probably updated to use Gtk.ListStore or something other than TreeView and CellRenderer but maybe that would be better left to a subsequent PR.

**Review by danrabbit — APPROVED** [review]

**Comment by danrabbit** [comment]
This looks good. Thanks for porting!

**Pull request merged**
