### PR TITLE
Fix a grammatical error

### PR DESCRIPTION
**Pull request by getsnoopy**
There should be a space between the number and its symbol, so this PR fixes this issue.

### CODE REVIEW

**Comment by jeremypw** [comment]
I am not sure this correct.  "24h" is not an abbreviation for "24 hours" (a number of units); it is an abbreviation for "24 hour" (adjectival phrase) as in "24 hour clock".  A quick Google search indicated that "24h" is more common in this case".

**Comment by tintou** [comment]
In any case, please do not make any change to .po and .pot files, those are made automatically :slightly_smiling_face:

**Comment by getsnoopy** [comment]
@jeremypw "24 h" is correct for both the adjectival and the nominal, [as per the SI](https://www.bipm.org/utils/common/pdf/si-brochure/SI-Brochure-9-EN.pdf#page=35). When written out, it would be "24-hour" vs. "24 hours".

@tintou Thanks for the tip. It seemed like those were "keys" for a lookup table, so I changed all of them. I'll remove those changes.

**Comment by jeremypw** [comment]
@getsnoopy As far as I can see, the SI deals only with scientific units, not descriptions of time formats. The word "clock" only appears twice in the document, neither place refer to time formats.  Please specify where the SI refers to the adjectival use for time formats.

**Comment by jeremypw** [comment]
Try typing "24h" and "24 h" into Wikipedia search and see what you get.

**Comment by getsnoopy** [comment]
@jeremypw Time is fundamentally a scientific unit, and they are included as part of the SI. The document (or the SI in general) doesn't distinguish between time units vs. non-time units in terms of formatting, since they all follow the same rules. E.g., 10 kilometres per _hour_ would be properly formatted as 10 km/h, so similarly, 10 hours would be formatted as 10 h. The time units are mentioned on pages 16 and 31 (130 and 145 in the printed page numbers, respectively).

**Comment by cassidyjames** [comment]
Here's the context:

image

I feel like we have plenty of room for the more clear "24-hour" label, so we should just do that. :)

**Comment by jeremypw** [comment]
@getsnoopy  I disagree - I think you are using scientific units out of context.  In any case what matters more is what is actually being used by the general public.  But as @cassidyjames says, the best solution would be not to abbreviate where not necessary and avoid the argument altogether :-)

**Comment by getsnoopy** [comment]
Updated

**Pull request merged**
